initial commit
coingate/coingate-node pull request #1
Opened 2022-09-27 10:03 UTC by arnasledev

initial commit message

2022-09-30 10:51 UTC, vgumonis requested changes
a github action is also required to run linter and tests. if either of them fails the action should also fail

2022-09-30 10:51 UTC, vgumonis commented on README.md
> +
document that async should be used

```
(async () => {
try {
  const order = await client.order.createOrder(data);
} catch (error) {
  // Oops... Something went wrong...
  console.error(error);
}
})();
```
or that can be used with promises
`client.order.createOrder(data).then(order => console.log(order)).catch(error => console.log(error))`

2022-09-30 10:51 UTC, vgumonis commented on src/Modules/Public/Public.service.ts
> +  public ipAddresses(separator?: string) {
rename to `getIPAddresses() `as in the readme

2022-09-30 10:51 UTC, vgumonis commented on src/Modules/Public/Public.service.ts
> +    return this.getCurrencies({
should also be` enabled=true`

2022-09-30 10:51 UTC, vgumonis commented on src/Modules/Public/Public.service.ts
> +  public getMerchantPayoutCurrencies(kind?: CurrencyKindEnum) {
`currencies?&enabled=true&merchant_receive=true&kind=kind`
document in the readme that kind can be passed

2022-09-30 10:51 UTC, vgumonis commented on src/Modules/Public/Public.service.ts
> +  public getMerchantPayCurrencies(kind?: CurrencyKindEnum) {
`currencies?&enabled=true&merchant_pay=true`

kind is not needed as this will always be crypto

2022-09-30 10:51 UTC, vgumonis commented on README.md
> +#### Test API Connection
document that testConnection returns boolean

2022-09-30 10:51 UTC, vgumonis commented on README.md
> +```
`setAppInfo` and `setTimeout ` are not documented

2022-09-30 10:51 UTC, vgumonis commented on src/Modules/Client/CoinGate.client.ts
> +  private getDefaultHeaders(requestType: RequestTypeEnum, apiKey?: string) {
dont mix private and public method , they should be grouped

2022-09-30 10:51 UTC, vgumonis commented on src/Exception/types.ts
> +  ITERNAL_SERVER_ERROR = 500,
typo

2022-09-30 10:51 UTC, vgumonis commented on build/Exception/ErrorHandler.js
> +            case types_1.HttpStatusEnum.ITERNAL_SERVER_ERROR | types_1.HttpStatusEnum.GATEWAY_TIMEOUT:
typo

2022-10-07 10:59 UTC, arnasledev commented
@vgumonis updated

2022-10-07 13:24 UTC, vgumonis requested changes
fix examples
and please revert the name to coingate-client (sorry about that one)
planning on publishing the package on monday

2022-10-07 13:24 UTC, vgumonis commented on examples/public/index.ts
> +const getIpAdresses = async () => {
typo

2022-10-07 13:24 UTC, vgumonis commented on examples/public/index.ts
> +    const addresses = await client.public.ipAddresses(separator);
wrong method name

2022-10-07 13:24 UTC, vgumonis commented
@arnasledev

2022-10-10 09:26 UTC, vgumonis commented
@arnasledev there is still many references to` coingate-sdk`

2022-10-10 12:39 UTC, vgumonis approved these changes

2022-10-10 12:39 UTC, merged